# Generated by Django 4.1.7 on 2023-09-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contract", "0002_delete_contract"),
        ("property", "0002_alter_property_location_delete_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Property",
        ),
    ]
