# Generated by Django 4.2.5 on 2023-09-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('owner', models.CharField(max_length=50)),
                ('amount', models.BigIntegerField()),
                ('timeReadyToMoveIn', models.DateField()),
                ('apartmentSize', models.IntegerField()),
                ('highlights', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('overallRating', models.FloatField(max_length=3)),
            ],
        ),
    ]
