# Generated by Django 4.1.4 on 2023-10-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twentyfiveacres", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="rent_duration",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "1 months"),
                    (2, "2 months"),
                    (3, "3 months"),
                    (4, "4 months"),
                    (5, "5 months"),
                    (6, "6 months"),
                    (7, "7 months"),
                    (8, "8 months"),
                    (9, "9 months"),
                    (10, "10 months"),
                    (11, "11 months"),
                    (12, "12 months"),
                ],
                null=True,
            ),
        ),
    ]
