# Generated by Django 4.1.7 on 2023-09-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twentyfiveacres", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("booking", "Booking"),
                    ("down_payment", "Down Payment"),
                    ("full_payment", "Full Payment"),
                    ("rent", "Rent"),
                ],
                max_length=20,
            ),
        ),
    ]
