# Generated by Django 4.2.5 on 2023-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
