# Generated by Django 4.2.5 on 2023-10-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0002_property_reported'),
    ]

    operations = [
        migrations.CreateModel(
            name='SHA',
            fields=[
                ('sha', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
    ]
