# Generated by Django 4.1.7 on 2023-09-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twentyfiveacres", "0002_remove_transaction_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller"), ("admin", "Admin")],
                max_length=20,
            ),
        ),
    ]
