# Generated by Django 4.2.5 on 2023-09-26 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0002_property_bidder_property_currentbid_property_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userType',
        ),
    ]
