# Generated by Django 4.1.7 on 2023-09-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twentyfiveacres", "0002_property_bidder_property_currentbid_property_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="city",
        ),
        migrations.RemoveField(
            model_name="location",
            name="country",
        ),
        migrations.RemoveField(
            model_name="location",
            name="state",
        ),
        migrations.RemoveField(
            model_name="location",
            name="streetAddress",
        ),
        migrations.RemoveField(
            model_name="location",
            name="zipCode",
        ),
        migrations.AddField(
            model_name="location",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
    ]
