# Generated by Django 4.2.5 on 2023-10-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0002_user_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='buyerContract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_buyer_contract', to='twentyfiveacres.buyercontract'),
        ),
    ]
