# Generated by Django 4.1.4 on 2023-10-27 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("twentyfiveacres", "0002_property_rent_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="monthsRemaining",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
