# Generated by Django 4.1.7 on 2023-09-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "twentyfiveacres",
            "0003_remove_location_city_remove_location_country_and_more",
        ),
        ("twentyfiveacres", "0003_remove_user_usertype"),
    ]

    operations = []
