# Generated by Django 4.2.5 on 2023-10-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0003_sha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code',
            new_name='verificationCode',
        ),
    ]
