# Generated by Django 4.2.5 on 2023-09-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contract',
        ),
    ]
