# Generated by Django 4.2.5 on 2023-09-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0003_remove_location_city_remove_location_country_and_more'),
        ('twentyfiveacres', '0003_remove_user_usertype'),
    ]

    operations = [
    ]
