# Generated by Django 4.1.7 on 2023-09-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("twentyfiveacres", "0004_delete_contract"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("contract_id", models.AutoField(primary_key=True, serialize=False)),
                ("contract_text", models.TextField()),
                ("contract_hash", models.CharField(max_length=64)),
                (
                    "contract_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buyer_contracts",
                        to="twentyfiveacres.user",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="twentyfiveacres.property",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_contracts",
                        to="twentyfiveacres.user",
                    ),
                ),
            ],
        ),
    ]
