# Generated by Django 4.2.5 on 2023-09-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0004_merge_20230926_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='propertyType',
        ),
    ]
