# Generated by Django 4.2.5 on 2023-10-19 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0004_delete_sha_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transactionId', models.AutoField(primary_key=True, serialize=False)),
                ('withPortal', models.BooleanField(default=False)),
                ('amount', models.IntegerField(default=1000000000)),
                ('credit', models.BooleanField(default=True)),
                ('debit', models.BooleanField(default=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('other', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_other_user_relation', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_user_relation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
