# Generated by Django 4.1.7 on 2023-09-20 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("twentyfiveacres", "0005_contract"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contract",
        ),
    ]
