# Generated by Django 4.2.5 on 2023-09-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0004_merge_20230926_2211'),
        ('twentyfiveacres', '0005_remove_property_propertytype'),
    ]

    operations = [
    ]
