# Generated by Django 4.1.7 on 2023-09-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twentyfiveacres", "0007_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="document_hash",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
