# Generated by Django 4.2.5 on 2023-09-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0008_alter_property_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='transaction_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('initiated_by_seller', 'Initiated by Seller'), ('initiated_by_buyer', 'Initiated by Buyer'), ('completed', 'Completed')], default='not_started', max_length=20),
        ),
    ]
