# Generated by Django 4.2.5 on 2023-10-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twentyfiveacres', '0010_alter_property_currentbid_alter_property_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contractText',
        ),
        migrations.AddField(
            model_name='contract',
            name='verfiedByBuyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='verfiedByPortal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='verfiedBySeller',
            field=models.BooleanField(default=False),
        ),
    ]
