# Generated by Django 4.1.7 on 2023-09-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("property", "0003_delete_property"),
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
