# Generated by Django 4.2.5 on 2023-09-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
