# Generated by Django 4.2.5 on 2023-09-24 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_delete_user'),
        ('user', '0002_user_aadhar_number_user_document_hash'),
    ]

    operations = [
    ]
