# Generated by Django 4.2.5 on 2023-09-25 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_merge_20230924_2355'),
        ('user', '0003_merge_20230925_1708'),
    ]

    operations = [
    ]
